"""folollowers

Revision ID: 649ab87d21a6
Revises: 5d719eff4a00
Create Date: 2022-06-12 09:05:42.076102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649ab87d21a6'
down_revision = '5d719eff4a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
